export const ROUTES = {
  NEW_COURSE: "/",
  APPLICATION: "/application",
  FORM_SUBMITTED: "/submitted",
  HOME: "/login",
  DASHBOARD: "/dashboard",
  PAYMENT: "/payment",
  LECTURE: "/lecture/:id",
  QUIZ: "/assignment",
  WORD: "/word",
  ASSIGNMENT: "/module/assignment",
  BANKTRANSFER: "/banktransfer",
  CONGRATULATIONS: "/success",
  LECTURECOMPLETE: "/lecture-success",
  EVENTS: "/events",
};
